// This file is auto-generated by @hey-api/openapi-ts

export const PlaylistSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            example: 'playlist-123'
        },
        name: {
            type: 'string',
            example: 'My Playlist'
        },
        user_id: {
            type: 'string',
            example: 'user-123'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            example: '2021-01-01T00:00:00Z'
        }
    }
} as const;

export const SongSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            example: 'song-123'
        },
        name: {
            type: 'string',
            example: 'My Song'
        },
        playlist_id: {
            type: 'string',
            example: 'playlist-123'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            example: '2021-01-01T00:00:00Z'
        }
    }
} as const;

export const UpdateSongRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Updated Song Name'
        }
    }
} as const;