// This file is auto-generated by @hey-api/openapi-ts

export const PlaylistSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'number',
            example: 123
        },
        title: {
            type: 'string',
            example: 'My Playlist'
        },
        user_id: {
            type: 'string',
            example: 'user-123'
        },
        songs: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Song'
            }
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            example: '2021-01-01T00:00:00Z'
        }
    }
} as const;

export const SongSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'number',
            example: 123
        },
        title: {
            type: 'string',
            example: 'My Song'
        },
        artist: {
            type: 'string',
            example: 'My Artist'
        },
        playlist_id: {
            type: 'string',
            example: 'playlist-123'
        },
        image_url: {
            type: 'string',
            example: 'https://example.com/image.jpg'
        },
        tracks: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Track'
            }
        },
        song_key: {
            type: 'string',
            example: 'C'
        },
        tempo_changes: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    tempo: {
                        type: 'number',
                        example: 120
                    }
                }
            }
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            example: '2021-01-01T00:00:00Z'
        }
    }
} as const;

export const TrackSchema = {
    required: ['name', 'url'],
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'track-123'
        },
        url: {
            type: 'string',
            example: 'https://example.com/file.mp3'
        }
    }
} as const;

export const UpdateSongRequestSchema = {
    type: 'object',
    '$ref': '#/components/schemas/Song'
} as const;

export const DownloadStemsRequestSchema = {
    type: 'object',
    properties: {
        stems: {
            type: 'array',
            items: {
                type: 'string'
            },
            example: ['vocals', 'drums', 'bass', 'other']
        },
        file_type: {
            type: 'string',
            example: 'mp3'
        }
    }
} as const;