'use client'

import { Inter } from 'next/font/google'
import Providers from '@/components/Providers'
import NavBar from '@/components/NavBar'
import GlobalSnackbar from '@/components/GlobalSnackbar'
import { Box } from '@mui/material'

import './globals.css'
import '@fontsource/roboto/300.css'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'
import AuthGuard from '@/components/AuthGuard'
import { useAtomValue } from 'jotai'
import { userAtom } from '@/state/user'

import '@/lib/axios'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const user = useAtomValue(userAtom)

  return (
    <html lang="en">
      <head>
        <script src="https://accounts.google.com/gsi/client" async></script>
      </head>
      <body className={inter.className}>
        <AuthGuard>
          <Providers>
            <Box
              sx={{
                display: 'flex',
                bgcolor: 'background.default',
                height: 1,
                flexDirection: 'column',
                width: 1,
              }}
            >
              {!!user && <NavBar />}

              <Box
                sx={{
                  bgcolor: 'background.default',
                  width: 1,
                  height: 1,
                }}
              >
                <Box
                  component="main"
                  sx={{ bgcolor: 'background.default', height: 1 }}
                >
                  {children}
                  <GlobalSnackbar />
                </Box>
              </Box>
            </Box>
          </Providers>
        </AuthGuard>
      </body>
    </html>
  )
}
