import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '@/components/Providers'
import NavBar from '@/components/NavBar'
import { Box, Container } from '@mui/material'

import './globals.css'
import '@fontsource/roboto/300.css'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'
import AuthGuard from '@/components/AuthGuard'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthGuard>
          <Providers>
            <Box sx={{ display: 'flex', background: '#eee' }}>
              <NavBar />
              <Box sx={{ width: 1 }}>
                <Box component="main">{children}</Box>
              </Box>
            </Box>
          </Providers>
        </AuthGuard>
      </body>
    </html>
  )
}
